//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Log
    {
        [DisplayName("Type: ")]
        [Required(ErrorMessage ="This field is requiered.")]
        public string type { get; set; }
        [DisplayName("Severity: ")]
        public string severity { get; set; }
        [DisplayName("Date: ")]
        public string date { get; set; }
        [DisplayName("Author: ")]
        public string author { get; set; }
        [DisplayName("Message: ")]
        public string message { get; set; }
        public int logID { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public Log()
        {
            
        }
    }
}
