//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [DisplayName("Name: ")]
        [Required(ErrorMessage ="This field is required..")]
        public string name { get; set; }

        [Required(ErrorMessage = "This field is required..")]
        [DisplayName("Password: ")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public string email { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
